name: Check Examples
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globber:
          - "askama-[a-i]"
          - "askama-[j-z]"
          - "[b-e]"
          - "[f-j]"
          - "[k-n]"
          - "[p-z]"
    steps:
      - name: Checkout site source
        uses: actions/checkout@v6

      - name: install cpanm and multiple modules
        uses: perl-actions/install-with-cpanm@v2
        with:
          install: |
            IPC::Run
            LWP::UserAgent

      - name: show environment
        run: |
          rustc -vV
          perl -v
          prove --version
      - name: run tests
        env:
            EXAMPLES: ${{matrix.globber}}
        run: prove -v check_examples.t




