name: Check Examples
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site source
        uses: actions/checkout@v6

      - name: install cpanm and multiple modules
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: |
            IPC::Run
            Test::Parallel

      - name: show environment
        run: |
          rustc -vV
          perl -v
          proove --version
      - name: run tests
        run: prove check_examples.t




